[package]
name = "kv"
version = "0.9.3"
authors = ["Zach Shipko <zachshipko@gmail.com>"]
license = "ISC"
keywords = ["key-value-store", "database", "lmdb"]
repository = "https://github.com/zshipko/rust-kv"
documentation = "https://docs.rs/kv"
description = "An embedded key/value store for Rust"
readme = "README.md"
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[dependencies]
thiserror = "1.0.9"
lmdb-rkv = "0.12"
serde = {version = "1.0", features=["derive"]}
toml = "0.5"
bincode = { version = "1.0", optional = true }
serde_cbor = { version = "0.10", optional = true }
serde_json = { version = "1.0", optional = true }
rmp-serde = { version = "0.14", optional = true }

[features]
default = []
cbor-value = ["serde_cbor"]
json-value = ["serde_json"]
bincode-value = ["bincode"]
msgpack-value = ["rmp-serde"]
